import "$style@globals.css";
import type { Metadata } from "next";
import { poppins } from "$utils@fonts";
import navVariants from "$component@nav";
import { cookies } from "next/headers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/logo.png",
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const theme = cookies().get("theme");
    return (
        <html lang="en" className={theme?.value}>
            <body
                className={
                    poppins.className +
                    "text-color dark:text-color-dark autumn:text-color-autumn bg-bg-light dark:bg-bg-dark autumn:bg-bg-autumn"
                }
            >
                <navVariants.navbar />
                {children}
            </body>
        </html>
    );
}
