import "$style@globals.css";
import type { Metadata } from "next";
import { poppins } from "$utils@fonts";
import navVariants from "$component@nav";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <navVariants.navbar />
                {children}
            </body>
        </html>
    );
}
