name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
 send_embed:
    runs-on: ubuntu-latest
    name: Send an embed to Discord

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
